Drop table if exists HITS;

Create table if not exists HITS
(
    ID        bigint generated by default as identity not null,
    APP       varchar(64)                             not null,
    URI       varchar(255)                            not null,
    IP        varchar(32)                             not null,
    TIMESTAMP timestamp without time zone             not null,
    constraint PK_BOOKINGS
        primary key (ID)
);